version: '3.1'

services:
  db:
    image: pandorafms/pandorafms-percona-base
    restart: always
    #command: ["mysqld", "--innodb-buffer-pool-size=900M"]
    environment:
      MYSQL_ROOT_PASSWORD: pandora
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: pandora
    networks:
     - pandora

  pandora:
    image: pandorafms/pandorafms-open-stack-el8:grafana
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: pandora
      DBHOST: db
      DBNAME: pandora
      DBUSER: pandora
      DBPASS: pandora
      DBPORT: 3306
      INSTANCE_NAME: pandora01
      PUBLICURL: ""
      SLEEP: 5
      RETRIES: 10
    networks:
     - pandora
    ports:
      - "8080:80"
      - "41121:41121"
      - "162:162/udp"
      - "9995:9995/udp"

  grafana:
    restart: always
    hostname: grafana
    image: grafana/grafana:7.0.0
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: 'https://github.com/projects-pandorafms/pandorafms-datasource/releases/download/1.0/pandorafms-datasource.zip;pandorafms-datasource'
    networks:
     - pandora

networks:
  pandora:
